
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package mz.ex.ws;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-09-17T11:34:21.250-03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(endpointInterface = "mz.ex.ws.BookRepo", serviceName = "BookRepoService")                      
public class BookRepoImpl implements BookRepo {

    public mz.ex.ws.BookResponse getBook(mz.ex.ws.BookRequest arg0) {  
        System.out.println(arg0);    
        try {
            mz.ex.ws.BookResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
 
    }

}