
package mz.ex.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-25T16:28:56.881-03:00
 * Generated source version: 3.1.10
 * 
 */

@WebService(portName = "BookRepoPort", serviceName = "BookRepoService")
public interface BookRepoPortType {
	@WebMethod(operationName = "GetBook")
    @WebResult(name = "book", targetNamespace = "")
    public mz.ex.ws.BookResponse getBook(
        mz.ex.ws.BookRequest arg0
    );
}
