
package mz.ex.ws;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-25T16:46:26.883-03:00
 * Generated source version: 3.1.10
 * 
 */

@WebService
public interface BookRepoImpl_PortType {

    public mz.ex.ws.BookResponse getBook(
        mz.ex.ws.BookRequest arg0
    );
}
