package mz.ex.ws;

/**
 * This class was generated by Apache CXF 3.1.10 2017-04-25T10:28:30.414-03:00 Generated source version: 3.1.10
 * 
 */
public class BookRepoClient {

	public static void main(String[] args) throws Exception {
		/*
		 * Este truststore tiene que tener importado el certificado del keystore generado para encriptar las conexiones
		 * ssl de tomcat.
		 * 
		 * 
		 * Se debe agregar la siguiente configuracion al server de tomcat en conf/server.xml:
		 * 
		 * <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol" maxThreads="150"
		 * SSLEnabled="true" keystoreFile="conf/serverKeystore.jks" keystorePass="password"> <SSLHostConfig>
		 * <Certificate certificateKeystoreFile="conf/serverKeystore.jks" certificateKeystorePassword="password"
		 * type="RSA" /> </SSLHostConfig> </Connector>
		 */
		System.setProperty("javax.net.ssl.trustStore", "cert/clienttruststore.jks");
		System.setProperty("javax.net.ssl.trustStorePassword", "password");

		/* ESTAS LINEAS SON PARA VISUALIZAR LOS MENSAJES SOAP ENVIADOS */
		System.setProperty("com.sun.xml.ws.transport.http.client.HttpTransportPipe.dump", "true");
		System.setProperty("com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.dump", "true");
		System.setProperty("com.sun.xml.ws.transport.http.HttpAdapter.dump", "true");
		System.setProperty("com.sun.xml.internal.ws.transport.http.HttpAdapter.dump", "true");

		// QName serviceName = new QName("http://ws.ex.mz/", "BookRepoService");
		// QName portName = new QName("http://ws.ex.mz/", "BookRepoPort");
		// URL wsdlUrl = BookRepoPortType.class.getClassLoader().getResource("BookRepoPortTypeImpl.wsdl");
		//
		// Service service = Service.create(wsdlUrl, serviceName);
		// service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
		// "https://localhost:8443/CxfMavenSslUsernametoken-0.0.1/services/BookRepo");
		// BookRepoPortType client = service.getPort(portName, BookRepoPortType.class);
		//
		// BookRequest bookRequest = new BookRequest();
		// bookRequest.setIsbn(1234L);
		// BookResponse bookResponse = client.getBook(bookRequest);
		// System.out.printf("Got book %s:%s %n", bookResponse.getIsbn(), bookResponse.getName());

		BookRepoService bookRepoService = new BookRepoService();
		BookRepoPortType port = bookRepoService.getBookRepoPort();
		BookRequest bookRequest = new BookRequest();
		bookRequest.setIsbn(1234L);
		port.getBook(bookRequest);
	}

}